const produtosDigital = () => (window.dadosCardapioApexFood?.produtos || []).filter(produto => produto.disponibilidade);
const categoriasDigital = () => window.dadosCardapioApexFood?.categorias || [];
let categoriaDigitalAtiva = 'todas';
function renderizarQrVisual() { const marcadores = new Set([0,1,2,3,4,5,6,7,8,9,17,18,26,27,35,36,44,45,53,54,62,63,71,72,73,74,75,76,77,78,79,80,12,13,21,22,40,41,49,50,58,59]); document.getElementById('qrVisual').innerHTML = Array.from({ length: 81 }, (_, indice) => `<span class="rounded-sm ${marcadores.has(indice) ? 'bg-black' : 'bg-white'}"></span>`).join(''); }
function moedaDigital(valor) { return window.ferramentasInterfaceApexFood?.formatarMoeda ? window.ferramentasInterfaceApexFood.formatarMoeda(valor) : Number(valor || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function escapeDigital(valor) { return window.ferramentasInterfaceApexFood?.escaparHtml ? window.ferramentasInterfaceApexFood.escaparHtml(valor) : String(valor ?? ''); }
function renderizarPreviewDigital() { const categorias = [{ id: 'todas', nome: 'Todos' }, ...categoriasDigital()]; document.getElementById('categoriasPreview').innerHTML = categorias.map(categoria => `<button type="button" data-categoria-preview="${categoria.id}" class="cardapio-tab ${categoriaDigitalAtiva === categoria.id ? 'ativa' : ''} whitespace-nowrap px-3 py-2 rounded-full border border-neutral-200 text-xs font-medium text-neutral-500 hover:text-neutral-900 transition">${escapeDigital(categoria.nome)}</button>`).join(''); const lista = produtosDigital().filter(produto => categoriaDigitalAtiva === 'todas' || produto.categoria === categoriaDigitalAtiva); document.getElementById('produtosPreview').innerHTML = lista.map(produto => `<article class="rounded-xl border border-neutral-200 p-4 flex items-center justify-between gap-3"><div class="min-w-0"><div class="flex items-center gap-2"><h4 class="text-sm font-semibold truncate">${escapeDigital(produto.nome)}</h4>${produto.destaque ? '<span class="px-1.5 py-0.5 rounded bg-orange-100 text-orange-700 text-[9px] font-semibold">Destaque</span>' : ''}</div><p class="text-xs text-neutral-500 line-clamp-2 mt-1">${escapeDigital(produto.descricao)}</p></div><strong class="text-sm text-orange-600 whitespace-nowrap">${moedaDigital(produto.preco)}</strong></article>`).join(''); document.querySelectorAll('[data-categoria-preview]').forEach(botao => botao.addEventListener('click', () => { categoriaDigitalAtiva = botao.dataset.categoriaPreview; renderizarPreviewDigital(); })); window.lucide?.createIcons(); }
document.querySelectorAll('.modo-preview').forEach(botao => botao.addEventListener('click', () => { document.querySelectorAll('.modo-preview').forEach(item => { const ativo = item === botao; item.classList.toggle('ativa', ativo); item.classList.toggle('text-accent', ativo); item.classList.toggle('text-muted', !ativo); }); const preview = document.getElementById('previewCardapio'); preview.classList.toggle('max-w-sm', botao.dataset.modo === 'mobile'); preview.classList.toggle('max-w-3xl', botao.dataset.modo !== 'mobile'); }));
document.getElementById('publicarCardapio').addEventListener('click', () => mostrarAvisoPedido('Alterações publicadas no Cardápio Digital.')); document.getElementById('copiarLinkCardapio').addEventListener('click', () => mostrarAvisoPedido('Link do cardápio copiado para compartilhamento.')); document.getElementById('baixarQr').addEventListener('click', () => mostrarAvisoPedido('QR Code preparado para download.'));
function atualizarPreviewDigital() { renderizarPreviewDigital(); }
renderizarQrVisual(); renderizarPreviewDigital(); window.lucide?.createIcons(); document.addEventListener('apex:cardapio-atualizado', atualizarPreviewDigital);
