const categoriasCardapio = window.dadosCardapioApexFood.categorias;
const elementosCategorias = { busca: document.getElementById('buscaCategoria'), lista: document.getElementById('listaCategorias') };
const coresCategorias = { green: 'text-green', orange: 'text-accent', yellow: 'text-yellow', blue: 'text-blue', purple: 'text-purple' };
function escapeCategoria(valor) { return window.ferramentasInterfaceApexFood?.escaparHtml ? window.ferramentasInterfaceApexFood.escaparHtml(valor) : String(valor ?? ''); }
function categoriasVisiveis() { const termo = elementosCategorias.busca.value.trim().toLocaleLowerCase('pt-BR'); return categoriasCardapio.filter(categoria => `${categoria.nome} ${categoria.descricao}`.toLocaleLowerCase('pt-BR').includes(termo)); }
function renderizarCategorias() { const lista = categoriasVisiveis(); document.getElementById('totalCategorias').textContent = categoriasCardapio.length; document.getElementById('totalProdutosCategoria').textContent = categoriasCardapio.reduce((total, categoria) => total + categoria.produtos, 0); document.getElementById('categoriaDestaque').textContent = categoriasCardapio.reduce((maior, categoria) => categoria.produtos > maior.produtos ? categoria : maior, categoriasCardapio[0]).nome; document.getElementById('resultadoCategorias').textContent = `${lista.length} ${lista.length === 1 ? 'categoria encontrada' : 'categorias encontradas'}.`; elementosCategorias.lista.innerHTML = lista.length ? lista.map(categoria => `<article class="cardapio-card rounded-xl bg-card2 border border-border2 p-5"><div class="flex items-start justify-between gap-3"><div class="cardapio-icon w-11 h-11 rounded-xl bg-${categoria.cor}/10 flex items-center justify-center"><i data-lucide="${categoria.icone}" class="w-5 h-5 ${coresCategorias[categoria.cor]}"></i></div><button type="button" data-editar-categoria="${categoria.id}" class="p-2 rounded-lg hover:bg-card text-muted" aria-label="Editar ${escapeCategoria(categoria.nome)}"><i data-lucide="more-horizontal" class="w-4 h-4"></i></button></div><h4 class="text-base font-semibold mt-4">${escapeCategoria(categoria.nome)}</h4><p class="text-xs text-muted leading-relaxed mt-1 min-h-8">${escapeCategoria(categoria.descricao)}</p><div class="flex items-center justify-between gap-3 mt-5 pt-4 border-t border-border"><span class="text-xs text-muted"><strong class="text-white">${categoria.produtos}</strong> ${categoria.produtos === 1 ? 'produto' : 'produtos'}</span><span class="flex items-center gap-1.5 text-xs text-green"><span class="w-1.5 h-1.5 rounded-full bg-green"></span> Ativa</span></div><div class="mt-3 text-[10px] text-muted">Destaque: <span class="text-white">${escapeCategoria(categoria.destaque)}</span></div></article>`).join('') : `<div class="sm:col-span-2 xl:col-span-3 rounded-lg border border-border2 border-dashed py-12 text-center"><i data-lucide="search-x" class="w-5 h-5 text-muted mx-auto mb-2"></i><p class="text-sm font-medium">Nenhuma categoria encontrada</p><p class="text-xs text-muted mt-1">Ajuste o termo da busca.</p></div>`; elementosCategorias.lista.querySelectorAll('[data-editar-categoria]').forEach(botao => botao.addEventListener('click', () => mostrarAvisoPedido('Edição de categoria preparada para a próxima integração.'))); window.lucide?.createIcons(); }
function abrirModalCategoria() { const modal = document.getElementById('modalCategoria'); modal.classList.add('aberto'); modal.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; document.getElementById('nomeCategoria').focus(); }
function fecharModalCategoria() { const modal = document.getElementById('modalCategoria'); modal.classList.remove('aberto'); modal.setAttribute('aria-hidden', 'true'); document.body.style.overflow = ''; document.getElementById('formCategoria').reset(); }
elementosCategorias.busca.addEventListener('input', renderizarCategorias); document.getElementById('novaCategoria').addEventListener('click', abrirModalCategoria); document.getElementById('fecharModalCategoria').addEventListener('click', fecharModalCategoria); document.getElementById('cancelarCategoria').addEventListener('click', fecharModalCategoria); document.getElementById('backdropCategoria').addEventListener('click', fecharModalCategoria); document.getElementById('formCategoria').addEventListener('submit', event => { event.preventDefault(); fecharModalCategoria(); mostrarAvisoPedido('Categoria salva no preview.'); }); document.addEventListener('keydown', event => { if (event.key === 'Escape') fecharModalCategoria(); });
renderizarCategorias(); window.lucide?.createIcons();
