'use strict';

const dadosFluxo = () => window.dadosFinanceirosApexFood || { fluxo: [], relatoriosMensais: [] };
function moedaFluxo(valor) { return window.ferramentasInterfaceApexFood?.formatarMoeda ? window.ferramentasInterfaceApexFood.formatarMoeda(valor) : Number(valor || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function escapeFluxo(valor) { return window.ferramentasInterfaceApexFood?.escaparHtml ? window.ferramentasInterfaceApexFood.escaparHtml(valor) : String(valor ?? ''); }
function avisoFluxo(mensagem) { if (typeof mostrarAvisoPedido === 'function') mostrarAvisoPedido(mensagem); }
function periodoFluxoAtual() { return document.getElementById('periodoFluxo').value; }
function dataIsoAgora() { const data = new Date(); return `${data.getFullYear()}-${String(data.getMonth() + 1).padStart(2, '0')}-${String(data.getDate()).padStart(2, '0')}`; }
function inicioPeriodoFluxo(valor) { const hoje = new Date(`${dataIsoAgora()}T00:00:00`); const inicio = new Date(hoje); if (valor === 'Últimos 30 dias') inicio.setDate(hoje.getDate() - 29); else if (valor === 'Este trimestre') inicio.setMonth(hoje.getMonth() - 2, 1); else inicio.setDate(1); return `${inicio.getFullYear()}-${String(inicio.getMonth() + 1).padStart(2, '0')}-${String(inicio.getDate()).padStart(2, '0')}`; }
function movimentacoesDoPeriodo() { const inicio = inicioPeriodoFluxo(periodoFluxoAtual()); return dadosFluxo().fluxo.filter(movimento => !movimento.dataIso || movimento.dataIso >= inicio); }
function movimentacoesFiltradas() { const busca = document.getElementById('buscaFluxo').value.trim().toLocaleLowerCase('pt-BR'); const tipo = document.getElementById('filtroTipoFluxo').value; const categoria = document.getElementById('filtroCategoriaFluxo').value; return movimentacoesDoPeriodo().filter(movimento => (!busca || `${movimento.descricao} ${movimento.categoria} ${movimento.origem}`.toLocaleLowerCase('pt-BR').includes(busca)) && (tipo === 'todos' || movimento.tipo === tipo) && (categoria === 'todos' || movimento.categoria === categoria)); }
function atualizarIndicadoresFluxo() { const dados = movimentacoesDoPeriodo(); const entradas = dados.filter(item => item.tipo === 'entrada').reduce((total, item) => total + Number(item.valor || 0), 0); const saidas = dados.filter(item => item.tipo === 'saida').reduce((total, item) => total + Number(item.valor || 0), 0); const resultado = entradas - saidas; document.getElementById('totalEntradasFluxo').textContent = moedaFluxo(entradas); document.getElementById('totalSaidasFluxo').textContent = moedaFluxo(saidas); document.getElementById('resultadoLiquidoFluxo').textContent = moedaFluxo(resultado); document.getElementById('margemFluxo').textContent = entradas ? `${Math.round((resultado / entradas) * 100)}%` : '—'; }
function renderizarGraficoFluxo() { const dados = dadosFluxo().relatoriosMensais || []; const maior = Math.max(...dados.flatMap(item => [Number(item.vendas || 0), Number(item.despesas || 0)]), 1); document.getElementById('graficoFluxo').innerHTML = dados.length ? dados.map(item => `<div class="flex-1 h-full flex flex-col justify-end items-center gap-1 min-w-7"><div class="flex items-end gap-0.5 h-full"><div title="Entradas ${moedaFluxo(item.vendas)}" class="financeiro-chart-bar w-2 sm:w-3 rounded-t bg-green" style="height:${Math.max(5, Math.round((Number(item.vendas || 0) / maior) * 100))}%"></div><div title="Saídas ${moedaFluxo(item.despesas)}" class="financeiro-chart-bar w-2 sm:w-3 rounded-t bg-red" style="height:${Math.max(5, Math.round((Number(item.despesas || 0) / maior) * 100))}%"></div></div><span class="text-[10px] text-muted">${escapeFluxo(item.mes)}</span></div>`).join('') : '<div class="w-full h-full flex items-center justify-center text-xs text-muted">Nenhum relatório disponível</div>'; }
function statusMovimentacao(status) { return { pendente: 'Pendente', conciliado: 'Conciliado', cancelada: 'Cancelada', excluida: 'Excluída' }[status] || status || 'Pendente'; }
function renderizarFluxo() { const lista = movimentacoesFiltradas(); document.getElementById('resultadoMovimentacoesFluxo').textContent = `${lista.length} ${lista.length === 1 ? 'movimentação encontrada' : 'movimentações encontradas'}.`; document.getElementById('estadoVazioFluxo').classList.toggle('hidden', Boolean(lista.length)); document.getElementById('listaFluxo').innerHTML = lista.map(item => `<tr class="border-b border-border hover:bg-card2/50 transition"><td class="p-4 text-xs text-muted">${escapeFluxo(item.data)}</td><td class="p-4"><div class="font-medium">${escapeFluxo(item.descricao)}</div><div class="text-[10px] text-muted mt-1">#${escapeFluxo(item.id)}</div></td><td class="p-4 text-xs">${escapeFluxo(item.categoria)}</td><td class="p-4 text-xs text-muted">${escapeFluxo(item.origem)}</td><td class="p-4 text-xs text-muted">${escapeFluxo(item.forma)}</td><td class="p-4 font-semibold ${item.tipo === 'entrada' ? 'text-green' : 'text-red'}">${item.tipo === 'entrada' ? '+' : '-'} ${moedaFluxo(item.valor)}</td><td class="p-4"><span class="status-financeiro ${escapeFluxo(item.status)} px-2.5 py-1 rounded-md text-xs font-medium">${escapeFluxo(statusMovimentacao(item.status))}</span></td><td class="p-4 text-right"><button type="button" data-acao-movimentacao="${escapeFluxo(item.id)}" class="p-2 rounded-lg hover:bg-card2 text-muted" aria-label="Atualizar movimentação"><i data-lucide="more-horizontal" class="w-4 h-4"></i></button></td></tr>`).join(''); document.querySelectorAll('[data-acao-movimentacao]').forEach(botao => botao.addEventListener('click', () => atualizarStatusMovimentacao(botao.dataset.acaoMovimentacao))); window.lucide?.createIcons(); }
function abrirModalFluxo() { const modal = document.getElementById('modalFluxo'); document.getElementById('formFluxo').reset(); modal.classList.add('aberto'); modal.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; document.getElementById('descricaoFluxo').focus(); }
function fecharModalFluxo() { const modal = document.getElementById('modalFluxo'); modal.classList.remove('aberto'); modal.setAttribute('aria-hidden', 'true'); document.body.style.overflow = ''; }
async function atualizarStatusMovimentacao(id) { const movimento = dadosFluxo().fluxo.find(item => String(item.id) === String(id)); if (!movimento || !window.dadosFinanceirosRemotoAtivo || !window.apexModulosApi) { avisoFluxo('Não foi possível atualizar a movimentação. Tente novamente.'); return; } const proximo = movimento.status === 'pendente' ? 'conciliado' : movimento.status === 'conciliado' ? 'cancelada' : movimento.status; if (proximo === movimento.status) { avisoFluxo('Esta movimentação não pode ser alterada.'); return; } try { await window.apexModulosApi.atualizarMovimentacaoFinanceira({ id: String(movimento.id), estado: proximo }); await window.apexFinanceiroRecarregar?.(); avisoFluxo('Status da movimentação atualizado.'); } catch (erro) { avisoFluxo(erro.message || 'Não foi possível atualizar a movimentação.'); } }
async function salvarFluxo(event) { event.preventDefault(); if (!window.dadosFinanceirosRemotoAtivo || !window.apexModulosApi) { avisoFluxo('Não foi possível salvar o lançamento. Tente novamente.'); return; } const payload = { tipo: document.getElementById('tipoFluxo').value, descricao: document.getElementById('descricaoFluxo').value.trim(), categoria: document.getElementById('categoriaFluxo').value, valor: document.getElementById('valorFluxo').value, origem: 'Manual', forma: 'Não informado', chaveIdempotencia: window.apexModulosApi.gerarChaveIdempotencia?.('movimentacao') }; try { await window.apexModulosApi.criarMovimentacaoFinanceira(payload); await window.apexFinanceiroRecarregar?.(); fecharModalFluxo(); avisoFluxo('Lançamento salvo.'); } catch (erro) { avisoFluxo(erro.message || 'Não foi possível salvar o lançamento.'); } }
document.getElementById('novoLancamentoFluxo').addEventListener('click', abrirModalFluxo); document.getElementById('fecharModalFluxo').addEventListener('click', fecharModalFluxo); document.getElementById('cancelarFluxo').addEventListener('click', fecharModalFluxo); document.getElementById('backdropFluxo').addEventListener('click', fecharModalFluxo); ['buscaFluxo', 'filtroTipoFluxo', 'filtroCategoriaFluxo'].forEach(id => document.getElementById(id).addEventListener(id === 'buscaFluxo' ? 'input' : 'change', renderizarFluxo)); document.getElementById('periodoFluxo').addEventListener('change', () => { atualizarIndicadoresFluxo(); renderizarFluxo(); }); document.getElementById('formFluxo').addEventListener('submit', salvarFluxo); document.addEventListener('keydown', event => { if (event.key === 'Escape') fecharModalFluxo(); }); function atualizarFluxoRemoto() { atualizarIndicadoresFluxo(); renderizarGraficoFluxo(); renderizarFluxo(); } atualizarIndicadoresFluxo(); renderizarGraficoFluxo(); renderizarFluxo(); window.lucide?.createIcons(); document.addEventListener('apex:financeiro-atualizado', atualizarFluxoRemoto); document.addEventListener('apex:financeiro-indisponivel', atualizarFluxoRemoto);
