const dadosFluxo = window.dadosFinanceirosApexFood;
function moedaFluxo(valor) { return window.ferramentasInterfaceApexFood?.formatarMoeda ? window.ferramentasInterfaceApexFood.formatarMoeda(valor) : Number(valor || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function escapeFluxo(valor) { return window.ferramentasInterfaceApexFood?.escaparHtml ? window.ferramentasInterfaceApexFood.escaparHtml(valor) : String(valor ?? ''); }
function movimentacoesFiltradas() { const busca = document.getElementById('buscaFluxo').value.trim().toLowerCase(); const tipo = document.getElementById('filtroTipoFluxo').value; const categoria = document.getElementById('filtroCategoriaFluxo').value; return dadosFluxo.fluxo.filter(movimento => (!busca || `${movimento.descricao} ${movimento.categoria} ${movimento.origem}`.toLowerCase().includes(busca)) && (tipo === 'todos' || movimento.tipo === tipo) && (categoria === 'todos' || movimento.categoria === categoria)); }
function atualizarIndicadoresFluxo() { const entradas = dadosFluxo.fluxo.filter(item => item.tipo === 'entrada').reduce((total, item) => total + item.valor, 0); const saidas = dadosFluxo.fluxo.filter(item => item.tipo === 'saida').reduce((total, item) => total + item.valor, 0); const resultado = entradas - saidas; document.getElementById('totalEntradasFluxo').textContent = moedaFluxo(entradas); document.getElementById('totalSaidasFluxo').textContent = moedaFluxo(saidas); document.getElementById('resultadoLiquidoFluxo').textContent = moedaFluxo(resultado); document.getElementById('margemFluxo').textContent = `${Math.round((resultado / Math.max(entradas, 1)) * 100)}%`; }
function renderizarGraficoFluxo() { const dados = dadosFluxo.relatoriosMensais; const maior = Math.max(...dados.flatMap(item => [item.vendas, item.despesas]), 1); document.getElementById('graficoFluxo').innerHTML = dados.map(item => `<div class="flex-1 h-full flex flex-col justify-end items-center gap-1 min-w-7"><div class="flex items-end gap-0.5 h-full"><div title="Entradas ${moedaFluxo(item.vendas)}" class="financeiro-chart-bar w-2 sm:w-3 rounded-t bg-green" style="height:${Math.max(5, Math.round((item.vendas / maior) * 100))}%"></div><div title="Saídas ${moedaFluxo(item.despesas)}" class="financeiro-chart-bar w-2 sm:w-3 rounded-t bg-red" style="height:${Math.max(5, Math.round((item.despesas / maior) * 100))}%"></div></div><span class="text-[10px] text-muted">${item.mes}</span></div>`).join(''); }
function renderizarFluxo() { const lista = movimentacoesFiltradas(); document.getElementById('resultadoMovimentacoesFluxo').textContent = `${lista.length} ${lista.length === 1 ? 'movimentação encontrada' : 'movimentações encontradas'}.`; document.getElementById('estadoVazioFluxo').classList.toggle('hidden', Boolean(lista.length)); document.getElementById('listaFluxo').innerHTML = lista.map(item => `<tr class="border-b border-border hover:bg-card2/50 transition"><td class="p-4 text-xs text-muted">${escapeFluxo(item.data)}</td><td class="p-4"><div class="font-medium">${escapeFluxo(item.descricao)}</div><div class="text-[10px] text-muted mt-1">#${escapeFluxo(item.id)}</div></td><td class="p-4 text-xs">${escapeFluxo(item.categoria)}</td><td class="p-4 text-xs text-muted">${escapeFluxo(item.origem)}</td><td class="p-4 text-xs text-muted">${escapeFluxo(item.forma)}</td><td class="p-4 font-semibold ${item.tipo === 'entrada' ? 'text-green' : 'text-red'}">${item.tipo === 'entrada' ? '+' : '-'} ${moedaFluxo(item.valor)}</td><td class="p-4"><span class="status-financeiro ${item.status} px-2.5 py-1 rounded-md text-xs font-medium">${item.status === 'conciliado' ? 'Conciliado' : item.status}</span></td><td class="p-4 text-right"><button type="button" class="p-2 rounded-lg hover:bg-card2 text-muted" aria-label="Ver movimentação"><i data-lucide="chevron-right" class="w-4 h-4"></i></button></td></tr>`).join(''); window.lucide?.createIcons(); }
function abrirModalFluxo() { const modal = document.getElementById('modalFluxo'); document.getElementById('formFluxo').reset(); modal.classList.add('aberto'); modal.setAttribute('aria-hidden', 'false'); document.body.style.overflow = 'hidden'; document.getElementById('descricaoFluxo').focus(); }
function fecharModalFluxo() { const modal = document.getElementById('modalFluxo'); modal.classList.remove('aberto'); modal.setAttribute('aria-hidden', 'true'); document.body.style.overflow = ''; }
document.getElementById('novoLancamentoFluxo').addEventListener('click', abrirModalFluxo); document.getElementById('fecharModalFluxo').addEventListener('click', fecharModalFluxo); document.getElementById('cancelarFluxo').addEventListener('click', fecharModalFluxo); document.getElementById('backdropFluxo').addEventListener('click', fecharModalFluxo); ['buscaFluxo','filtroTipoFluxo','filtroCategoriaFluxo'].forEach(id => document.getElementById(id).addEventListener(id === 'buscaFluxo' ? 'input' : 'change', renderizarFluxo)); document.getElementById('periodoFluxo').addEventListener('change', () => mostrarAvisoPedido('Período do fluxo atualizado no preview.')); document.getElementById('formFluxo').addEventListener('submit', event => { event.preventDefault(); fecharModalFluxo(); mostrarAvisoPedido('Lançamento salvo no preview.'); }); document.addEventListener('keydown', event => { if (event.key === 'Escape') fecharModalFluxo(); }); atualizarIndicadoresFluxo(); renderizarGraficoFluxo(); renderizarFluxo(); window.lucide?.createIcons();
